a_plus_b: a_plus_b.o
		g++ -o a_plus_b a_plus_b.o

a_plus_b.o:	a_plus_b.cpp
		g++ -c a_plus_b.cpp

max_pairwise_product: max_pairwise_product.o
		g++ -o max_pairwise_product max_pairwise_product.o

max_pairwise_product.o:	max_pairwise_product.cpp
		g++ -c max_pairwise_product.cpp